apiVersion: v1
kind: Service
metadata:
  name: omes-workers
  labels:
    prometheus.io/job: 'omes-workers'
    prometheus.io/scrape: 'true'
    prometheus.io/scheme: http
    prometheus.io/port: '9090'
    app.kubernetes.io/headless: 'true'
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 9090
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app: omes-workers
